# route: cloudkitchens
mutation ExecuteEaterCartOperations($input: ExecuteCartOperationsInput!, $includeItemIds: Boolean = false, $includeStoreDisplayFields: Boolean = false, $storeId: String!, $menuStoreId: ID!, $serviceSlug: String!) {
  executeCartOperations(input: $input) {
    ... on ExecuteCartOperationsSuccess {
      cart {
        ...EaterCartResponseFields
      }
      validationIssues {
        ...CartEaterValidationIssueFederated
      }
    }
    ... on ExecuteCartOperationsVersionConflict {
      expectedCurrentVersion
    }
    ... on ExecuteCartOperationsNotFound {
      _empty
    }
    ... on ExecuteCartOperationsError {
      operationIndex
      message
      code
    }
    ... on ExecuteCartOperationsInvalid {
      validationIssues {
        ...CartEaterValidationIssueFederated
      }
    }
  }
}

fragment EaterCartResponseFields on StoredCart {
  cartId
  storeId
  isProcessing
  version
  createdAt
  updatedAt
  orderId
  serviceSlug
  eaterCart {
    id
    storeId
    serviceSlug
    note
    couponCode
    couponEvaluationToken
    scheduledAt
    fulfillmentInfo {
      __typename
    }
    deliveryInfo {
      note
      address {
        ...CanonicalAddressFields
      }
    }
    customerItems {
      ...BasicOrderCustomerItem
    }
    tipForRestaurant {
      ...BasicMoney
    }
    cateringInfo {
      ...BasicEaterCateringInfo
    }
  }
  paymentDetails {
    ...PreOrderPaymentDetails
  }
}

fragment CanonicalAddressFields on CanonicalAddress {
  countryIso
  addressLocalized {
    addressType
    addressLines
    addressLocality
    addressPostalCode
    addressRegion
    streetNumber
    placeName
  }
  coordinate {
    latitude
    longitude
  }
  addressComponent {
    adminLevel1
    adminLevel2
    adminLevel3
    adminLevel4
    adminLevel5
    adminLocality1
    adminLocality2
    adminLocality3
    adminLocality4
    adminLocality5
    adminLocality6
    neighborhood
    buildingName
    buildingNumber
    secondaryAddressUnit
    country
    streetNumber
  }
}

fragment BasicOrderCustomerItem on OrderCustomerItem {
  customerItemId
  menuItem @include(if: $includeItemIds) {
    id
  }
  isCustomItem
  price {
    currencyCode
    units
    nanos
  }
  quantity
  name
  note
  contents {
    isAlcoholic
  }
  modifiers {
    ...BasicCustomerItemModifier
    modifiers {
      ...BasicCustomerItemModifier
      modifiers {
        ...BasicCustomerItemModifier
        modifiers {
          ...BasicCustomerItemModifier
          modifiers {
            ...BasicCustomerItemModifier
            modifiers {
              ...BasicCustomerItemModifier
            }
          }
        }
      }
    }
  }
  storeId
  store @include(if: $includeStoreDisplayFields) {
    ...StoreDisplayFields
  }
  source
}

fragment BasicCustomerItemModifier on CustomerItemModifier {
  modifierGroupId
  customerItemId
  menuItem @include(if: $includeItemIds) {
    id
  }
  name
  price {
    currencyCode
    units
    nanos
  }
  quantity
}

fragment StoreDisplayFields on RestrictedStore {
  id
  restrictedBrand {
    name
  }
  storefront(serviceSlug: $serviceSlug) {
    files {
      logoImage {
        url
      }
    }
  }
  settings(serviceSlug: $serviceSlug) {
    brandSlug
    locationSlug
  }
  restrictedFacility {
    ... on RestrictedFacility {
      timezone
      currencyCode
    }
  }
}

fragment BasicMoney on Money {
  currencyCode
  units
  nanos
}

fragment BasicEaterCateringInfo on CateringInfo {
  guestCount
}

fragment PreOrderPaymentDetails on EaterOrderPaymentDetails {
  total {
    ...BasicMoney
  }
  lineItems {
    ...EaterOrderLineItemFields
  }
  couponDiscount {
    ...BasicCouponDiscount
  }
  depositRequired {
    amount {
      ...BasicMoney
    }
  }
}

fragment EaterOrderLineItemFields on EaterOrderLineItem {
  descriptionRosettaKey
  value {
    ...BasicMoney
  }
  breakdown {
    descriptionRosettaKey
    value {
      ...BasicMoney
    }
    externalName
  }
  externalName
}

fragment BasicCouponDiscount on EaterCouponDiscount {
  couponCode
  discount {
    ...BasicMoney
  }
  discountAsPercentOfSubtotal
}

fragment CartEaterValidationIssueFederated on EaterValidationIssue {
  ...BasicEaterValidationIssue
  entityIds
  eaterCustomerItemEntitiesFederated(storeId: $storeId, serviceSlug: $serviceSlug) {
    id
    type
    minimumPurchased
    storeId
    loyaltyServiceSlug
    menuEntityPromoEaterCustomerDetail(
      storeId: $menuStoreId
      serviceSlug: $serviceSlug
    ) {
      __typename
      ... on MenuItemPromoEaterCustomerItem {
        name {
          value
        }
      }
    }
  }
  eaterCustomerMenuEntitiesFederated(storeId: $storeId, serviceSlug: $serviceSlug) {
    id
    type
    minimumPurchased
    storeId
    loyaltyServiceSlug
    menuEntityPromoEaterCustomerDetail(
      storeId: $menuStoreId
      serviceSlug: $serviceSlug
    ) {
      __typename
      ... on MenuItemPromoEaterCustomerItem {
        name {
          value
        }
      }
      ... on MenuItemPromoEaterCustomerCategory {
        name {
          value
        }
      }
    }
  }
}

fragment BasicEaterValidationIssue on EaterValidationIssue {
  issueType
  entityId
}
