"""PicnicService — ordering workflows on top of PicnicClient.

PicnicClient mirrors the API 1:1. This layer speaks in the terms a person
(or an LLM) uses — "tomorrow's lunch", "the Mori Teriyaki menu", "swap
Thursday's order" — and handles the bookkeeping the web app does:

  - resolving a local date to a delivery window at the eater's hub
  - finding which facility (kitchen) a restaurant belongs to
  - turning item/modifier ids into fully priced line items, validating
    modifier-group rules against the menu
  - trimming responses down to the fields worth reading

How Picnic office ordering works: every weekday at a hub is a *meal
calendar* slot. A calendar entry holds a meal (line items) and turns into a
real order at `placeOrderAt` (the entry id becomes the order id). Entries come
from the eater (`USER_ADDED`) or their rotation (`ROTATION_AUTOGENERATED`).
Once placed, an order can only be cancelled. The company stipend is applied
automatically as a deduction.
"""

from __future__ import annotations

import hashlib
import uuid
from collections.abc import Iterable
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from typing import Any
from zoneinfo import ZoneInfo

from pydantic import BaseModel, Field

from .client import PicnicClient
from .http_base_client import ResponseError

# ─────────────────────────────── Inputs ───────────────────────────────


class ModifierChoice(BaseModel):
    """One selected option inside an item's modifier group."""

    item_id: str = Field(description="Option id from the menu's modifier group `options`")
    quantity: int = Field(1, ge=1)
    group_id: str | None = Field(
        None, description="Modifier group id; inferred from the menu when omitted"
    )
    modifiers: list[ModifierChoice] = Field(
        default_factory=list, description="Choices for the option's own modifier groups, if any"
    )


class LineItem(BaseModel):
    """A menu item to put in the cart or on the meal calendar."""

    store_id: str
    item_id: str
    quantity: int = Field(1, ge=1)
    modifiers: list[ModifierChoice] = Field(default_factory=list)
    note: str = ""


class PicnicInputError(ValueError):
    """The request can't be satisfied as asked (bad date, invalid modifiers, ...)."""


# ─────────────────────────────── Helpers ──────────────────────────────


def money(m: dict[str, Any] | None) -> float | None:
    """Picnic Money `{units, nanos}` → dollars."""
    if not m:
        return None
    return round(int(m.get("units") or 0) + int(m.get("nanos") or 0) / 1e9, 2)


def meal_contents_hash(items: Iterable[dict[str, Any]]) -> str:
    """Port of the web app's meal hash: sha256 over sorted `id:qty` tokens,
    depth-first through modifiers, joined with `+`."""
    tokens: list[str] = []

    def walk(item: dict[str, Any]) -> None:
        tokens.append(f"{item['customerItemId']}:{item['quantity']}")
        for mod in sorted(item.get("modifiers") or [], key=lambda m: m["customerItemId"]):
            walk(mod)

    for item in sorted(items, key=lambda i: i["customerItemId"]):
        walk(item)
    return hashlib.sha256("+".join(tokens).encode()).hexdigest()


def _kv(pairs: list[dict[str, Any]] | None) -> dict[str, Any]:
    """GraphQL `[{key, value}]` maps → dict."""
    return {p["key"]: p["value"] for p in pairs or []}


def _tag(tag: str) -> str:
    return tag.removeprefix("TAG_").replace("_N_", " & ").replace("_", " ").title()


@dataclass(frozen=True, slots=True)
class DeliveryWindow:
    hub_id: str
    route_id: str
    facility_id: str
    name: str
    start: str  # ISO UTC, e.g. 2026-10-01T16:00:00Z
    end: str
    order_cutoff: str
    local_date: str

    @property
    def hub_order_constraint(self) -> dict[str, Any]:
        return {"hubId": self.hub_id, "routeId": self.route_id,
                "deliveryWindowStart": self.start, "deliveryWindowEnd": self.end}

    @property
    def cart_domain(self) -> dict[str, Any]:
        return {"hubDomain": {"hubId": self.hub_id, "deliveryWindowStart": self.start}}

    def view(self) -> dict[str, Any]:
        return {"date": self.local_date, "name": self.name, "start": self.start,
                "end": self.end, "order_cutoff": self.order_cutoff}


# ─────────────────────────────── Service ──────────────────────────────


class PicnicService:
    def __init__(self, client: PicnicClient):
        self.client = client
        self._hub: dict[str, Any] | None = None
        self._windows: dict[str, list[DeliveryWindow]] = {}
        self._store_facility: dict[tuple[str, str], str] = {}
        self._menus: dict[tuple[str, str], dict[str, Any]] = {}

    # ── Hub & windows ────────────────────────────────────────────────────

    async def hub(self) -> dict[str, Any]:
        """The eater's home hub (delivery location)."""
        if self._hub is None:
            viewer = await self.client.get_viewer()
            if not viewer.get("hubId"):
                raise PicnicInputError("No delivery hub selected on this Picnic account")
            today = date.today()
            self._hub = await self.client.get_hub(
                viewer["hubId"], today.isoformat(), (today + timedelta(days=1)).isoformat()
            )
        return self._hub

    async def delivery_windows(self, days: int = 7) -> list[DeliveryWindow]:
        hub = await self.hub()
        tz = ZoneInfo(hub["timezone"])
        start = datetime.now(tz).date()
        key = f"{start}:{days}"
        if key not in self._windows:
            data = await self.client.get_hub(
                hub["id"], start.isoformat(), (start + timedelta(days=days)).isoformat()
            )
            self._windows[key] = [
                DeliveryWindow(
                    hub_id=hub["id"],
                    route_id=r["routeId"],
                    facility_id=r["restrictedFacility"]["id"],
                    name=r["windowDisplayName"],
                    start=r["deliveryWindowStart"],
                    end=r["deliveryWindowEnd"],
                    order_cutoff=r["minOrderingLeadTime"],
                    local_date=_parse_ts(r["deliveryWindowStart"]).astimezone(tz).date().isoformat(),
                )
                for r in data["individualRoutes"]
            ]
        return self._windows[key]

    async def window(self, day: str | None = None) -> DeliveryWindow:
        """Resolve a local date (YYYY-MM-DD, 'today', 'tomorrow'; default: the
        next window still open for ordering) to a delivery window."""
        windows = await self.delivery_windows(days=14)
        hub = await self.hub()
        today = datetime.now(ZoneInfo(hub["timezone"])).date()
        if day in (None, ""):
            now = datetime.now(ZoneInfo("UTC"))
            open_windows = [w for w in windows if _parse_ts(w.order_cutoff) > now]
            if not open_windows:
                raise PicnicInputError("No open delivery windows in the next two weeks")
            return open_windows[0]
        target = {"today": today, "tomorrow": today + timedelta(days=1)}.get(day)
        target_str = target.isoformat() if target else day
        for w in windows:
            if w.local_date == target_str:
                return w
        available = ", ".join(w.local_date for w in windows) or "none"
        raise PicnicInputError(f"No delivery window on {target_str}. Available: {available}")

    # ── Restaurants & menus ──────────────────────────────────────────────

    async def list_restaurants(self, day: str | None = None) -> dict[str, Any]:
        w = await self.window(day)
        content = await self.client.get_hub_main_content(w.hub_order_constraint)
        stores = [t["value"] for t in content["taggedLayout"]["storeTiles"]]
        for s in stores:
            self._store_facility[(w.start, s["storeId"])] = s["facilityId"]
        return {"window": w.view(), "restaurants": [_store_view(s) for s in stores]}

    async def search(self, query: str, day: str | None = None) -> dict[str, Any]:
        w = await self.window(day)
        result = await self.client.search(query, w.hub_order_constraint)
        stores = _kv(result.get("storesMap")) | {s["storeId"]: s for s in result.get("stores") or []}
        for s in stores.values():
            self._store_facility[(w.start, s["storeId"])] = s["facilityId"]
        return {
            "window": w.view(),
            "restaurants": [_store_view(s) for s in result.get("stores") or []],
            "items": [
                {**_item_view(i), "restaurant": stores.get(i["storeId"], {}).get("brandName")}
                for i in result.get("items") or []
            ],
        }

    async def _facility_for(self, w: DeliveryWindow, store_id: str) -> str:
        if (w.start, store_id) not in self._store_facility:
            await self.list_restaurants(w.local_date)
        try:
            return self._store_facility[(w.start, store_id)]
        except KeyError:
            raise PicnicInputError(
                f"Restaurant {store_id} isn't delivering to your hub on {w.local_date}"
            ) from None

    async def _menu(self, w: DeliveryWindow, store_id: str) -> dict[str, Any]:
        if (w.start, store_id) not in self._menus:
            facility_id = await self._facility_for(w, store_id)
            self._menus[(w.start, store_id)] = await self.client.get_store_content(
                store_id, facility_id, w.hub_order_constraint
            )
        return self._menus[(w.start, store_id)]

    async def get_menu(self, store_id: str, day: str | None = None) -> dict[str, Any]:
        w = await self.window(day)
        store = await self._menu(w, store_id)
        menu = store["menu"]
        items = _kv(menu["items"])
        groups = _kv(menu["modifierGroups"])
        categories = _kv(menu["categories"])
        order = [cid for info in menu["menuInfos"] for cid in info["categoryIds"]]
        used_groups = {gid for i in items.values() for gid in i.get("modifierGroupIds") or []}
        return {
            "window": w.view(),
            "restaurant": _store_view(store),
            "categories": [
                {
                    "name": categories[cid]["name"],
                    "items": [_item_view(items[iid]) for iid in categories[cid]["itemIds"]
                              if iid in items],
                }
                for cid in order if cid in categories
            ],
            "modifier_groups": {
                gid: _group_view(groups[gid], items) for gid in used_groups if gid in groups
            },
        }

    # ── Building line items ──────────────────────────────────────────────

    async def build_customer_item(self, w: DeliveryWindow, line: LineItem) -> dict[str, Any]:
        """Price a LineItem against the menu and validate its modifiers."""
        menu = (await self._menu(w, line.store_id))["menu"]
        items, groups = _kv(menu["items"]), _kv(menu["modifierGroups"])
        item = items.get(line.item_id)
        if item is None:
            raise PicnicInputError(f"Item {line.item_id} is not on this restaurant's menu")
        if item.get("isSuspended") or item.get("itemStatus") != "ITEM_STATUS_AVAILABLE":
            raise PicnicInputError(f"{item['name']} is currently unavailable")
        return {
            "customerItemId": item["id"],
            "storeId": line.store_id,
            "name": item["name"],
            "quantity": line.quantity,
            "note": line.note,
            "price": item["priceData"]["price"],
            "modifiers": _build_modifiers(item, line.modifiers, items, groups),
        }

    # ── Cart ─────────────────────────────────────────────────────────────

    async def get_cart(self, day: str | None = None) -> dict[str, Any]:
        w = await self.window(day)
        return _cart_view(w, await self.client.get_cart(w.cart_domain))

    async def add_to_cart(self, line: LineItem, day: str | None = None) -> dict[str, Any]:
        w = await self.window(day)
        customer_item = await self.build_customer_item(w, line)
        resp = await self.client.add_cart_item(w.cart_domain, customer_item, str(uuid.uuid4()))
        return _cart_view(w, resp)

    async def update_cart_item(
        self, cart_item_id: str, quantity: int, day: str | None = None
    ) -> dict[str, Any]:
        w = await self.window(day)
        if quantity <= 0:
            resp = await self.client.remove_cart_item(w.cart_domain, cart_item_id)
        else:
            resp = await self.client.update_cart_item_quantity(w.cart_domain, cart_item_id, quantity)
        return _cart_view(w, resp)

    async def clear_cart(self, day: str | None = None) -> dict[str, Any]:
        w = await self.window(day)
        return _cart_view(w, await self.client.empty_cart(w.cart_domain))

    # ── Meal calendar (orders) ───────────────────────────────────────────

    async def get_schedule(self, include_past: bool = False) -> dict[str, Any]:
        schedule = await self.client.get_schedule()
        stores = _kv(schedule.get("storeDataMap"))
        now = datetime.now(ZoneInfo("UTC"))
        entries = [
            _entry_view(e, stores)
            for e in schedule["calendaringScheduleEntries"]
            if include_past or _parse_ts(e["deliveryInfo"]["deliveryWindowStart"]) >= now
        ]
        return {"rotation_enabled": schedule["rotationEnabled"], "entries": entries}

    async def _entry_for(self, w: DeliveryWindow) -> dict[str, Any] | None:
        schedule = await self.client.get_schedule()
        for e in schedule["calendaringScheduleEntries"]:
            if e["deliveryInfo"]["deliveryWindowStart"] == w.start and not e["state"].get("cancelledAt"):
                return e
        return None

    async def schedule_meal(
        self,
        day: str,
        items: list[LineItem] | None = None,
        *,
        from_cart: bool = False,
        replace: bool = False,
    ) -> dict[str, Any]:
        """Put a meal on the calendar for `day`. It is ordered automatically at
        the entry's `place_order_at`. Uses `items`, or the day's cart when
        `from_cart` (the cart is emptied afterwards)."""
        w = await self.window(day)
        if from_cart:
            cart = await self.client.get_cart(w.cart_domain)
            meal_items = [ci["customerItem"] for ci in cart["cart"]["customerItems"]]
        else:
            meal_items = [await self.build_customer_item(w, line) for line in items or []]
        if not meal_items:
            raise PicnicInputError("Nothing to schedule: pass items or fill the cart first")

        existing = await self._entry_for(w)
        if existing:
            if existing["state"].get("orderId"):
                raise PicnicInputError(
                    f"The {w.local_date} order was already placed "
                    f"(order {existing['state']['orderId']}); cancel it first"
                )
            if not replace:
                raise PicnicInputError(
                    f"There is already a meal scheduled for {w.local_date} "
                    f"(entry {existing['id']}); pass replace=true to swap it"
                )
            await self.client.remove_schedule_entry(existing["id"])

        entry_id = str(uuid.uuid4())
        await self.client.add_schedule_entry({
            "id": entry_id,
            "meal": {
                "mealContentsHash": meal_contents_hash(meal_items),
                "mealItems": [_meal_item(i) for i in meal_items],
            },
            "deliveryInfo": {"hubId": w.hub_id, "deliveryWindowStart": w.start},
            "source": "USER_ADDED",
        })
        if from_cart:
            await self.client.empty_cart(w.cart_domain)
        scheduled = await self.get_schedule()
        entry = next((e for e in scheduled["entries"] if e["entry_id"] == entry_id), None)
        return {"scheduled": entry, "replaced_entry_id": existing["id"] if existing else None}

    async def cancel(self, entry_or_order_id: str, reason: str = "REASON_OTHER") -> dict[str, Any]:
        """Cancel a day's meal: removes the calendar entry if it hasn't been
        ordered yet, otherwise cancels the placed order."""
        schedule = await self.client.get_schedule()
        entry = next(
            (e for e in schedule["calendaringScheduleEntries"] if e["id"] == entry_or_order_id
             or e["state"].get("orderId") == entry_or_order_id),
            None,
        )
        if entry and not entry["state"].get("orderId"):
            if entry["state"].get("cancelledAt"):
                return {"status": "already_cancelled", "entry_id": entry["id"]}
            await self.client.remove_schedule_entry(entry["id"])
            return {"status": "removed_from_calendar", "entry_id": entry["id"]}

        order_id = entry["state"]["orderId"] if entry else entry_or_order_id
        session = await self.client.refresh_session()
        result = await self.client.cancel_order(order_id, session["username"], reason)
        ok = str(result.get("success")).lower() == "true"
        return {
            "status": "order_cancelled" if ok else "cancel_failed",
            "order_id": order_id,
            "failure_reason": result.get("cancellationFailureReason"),
        }

    # ── Orders ───────────────────────────────────────────────────────────

    async def list_orders(self) -> list[dict[str, Any]]:
        return [_order_view(o) for o in await self.client.list_orders()]

    async def get_order(self, order_id: str) -> dict[str, Any]:
        return await self.client.get_order(order_id)


# ─────────────────────────────── Views ────────────────────────────────


def _parse_ts(ts: str) -> datetime:
    return datetime.fromisoformat(ts.replace("Z", "+00:00"))


def _store_view(s: dict[str, Any]) -> dict[str, Any]:
    rating = s.get("rating") or {}
    cutoff = next((b["earlyCutoff"] for b in s.get("badges") or [] if b.get("earlyCutoff")), None)
    return {
        "store_id": s["storeId"],
        "name": s["brandName"],
        "cuisines": [_tag(t) for t in s.get("tags") or []],
        "rating": round(rating["score"], 2) if rating.get("score") else None,
        "rating_count": rating.get("count"),
        "status": (s.get("storeStatus") or "").removeprefix("STORE_STATUS_").lower() or None,
        **({"order_by_local_time": cutoff} if cutoff else {}),
    }


def _item_view(i: dict[str, Any]) -> dict[str, Any]:
    view = {
        "item_id": i["id"],
        "store_id": i["storeId"],
        "name": i["name"],
        "price": money(i["priceData"]["price"]),
    }
    if i.get("description"):
        view["description"] = i["description"]
    if i.get("modifierGroupIds"):
        view["modifier_group_ids"] = i["modifierGroupIds"]
    if i.get("isSuspended") or i.get("itemStatus") not in (None, "ITEM_STATUS_AVAILABLE"):
        view["available"] = False
    return view


def _group_view(g: dict[str, Any], items: dict[str, Any]) -> dict[str, Any]:
    sel = g.get("selectionData") or {}
    return {
        "name": g["name"],
        "min": sel.get("minimumNumberOfChoices", 0),
        "max": sel.get("maximumNumberOfChoices"),
        "options": [
            {"item_id": iid, "name": items[iid]["name"], "price": money(items[iid]["priceData"]["price"]),
             **({"modifier_group_ids": items[iid]["modifierGroupIds"]}
                if items[iid].get("modifierGroupIds") else {})}
            for iid in g["itemIds"] if iid in items
        ],
    }


def _build_modifiers(
    item: dict[str, Any],
    choices: list[ModifierChoice],
    items: dict[str, Any],
    groups: dict[str, Any],
) -> list[dict[str, Any]]:
    group_ids = item.get("modifierGroupIds") or []
    by_group: dict[str, list[ModifierChoice]] = {gid: [] for gid in group_ids}
    def has_room(g: str) -> bool:
        hi = (groups[g].get("selectionData") or {}).get("maximumNumberOfChoices")
        return not hi or sum(c.quantity for c in by_group[g]) < hi

    for choice in choices:
        # Groups can share options (e.g. "protein" / "second protein"), so an
        # un-grouped choice goes to the first matching group with room left.
        candidates = [g for g in group_ids if choice.item_id in groups.get(g, {}).get("itemIds", [])]
        gid = choice.group_id or next((g for g in candidates if has_room(g)), None) or next(
            iter(candidates), None
        )
        if gid not in by_group:
            raise PicnicInputError(f"Option {choice.item_id} isn't a modifier of {item['name']}")
        if choice.item_id not in groups[gid]["itemIds"]:
            raise PicnicInputError(f"Option {choice.item_id} isn't in group '{groups[gid]['name']}'")
        by_group[gid].append(choice)

    built: list[dict[str, Any]] = []
    for gid, picked in by_group.items():
        group = groups.get(gid)
        if group is None:
            continue
        sel = group.get("selectionData") or {}
        lo, hi = sel.get("minimumNumberOfChoices") or 0, sel.get("maximumNumberOfChoices")
        count = sum(c.quantity for c in picked)
        if count < lo or (hi and count > hi):
            options = ", ".join(f"{items[i]['name']} ({i})" for i in group["itemIds"] if i in items)
            rule = f"exactly {lo}" if lo == hi else f"{lo}–{hi or 'any'}"
            raise PicnicInputError(
                f"{item['name']}: '{group['name']}' needs {rule} choice(s), got {count}. "
                f"Options: {options}"
            )
        for c in picked:
            option = items[c.item_id]
            built.append({
                "customerItemId": option["id"],
                "modifierGroupId": gid,
                "name": option["name"],
                "quantity": c.quantity,
                "price": option["priceData"]["price"],
                "modifiers": _build_modifiers(option, c.modifiers, items, groups),
            })
    return built


def _meal_item(ci: dict[str, Any]) -> dict[str, Any]:
    """CustomerItem → rotation meal item (same shape, name as plain string)."""

    def mod(m: dict[str, Any]) -> dict[str, Any]:
        return {"customerItemId": m["customerItemId"], "quantity": m["quantity"],
                "modifierGroupId": m.get("modifierGroupId"), "price": _money_input(m["price"]),
                "name": _plain_name(m["name"]), "modifiers": [mod(x) for x in m.get("modifiers") or []]}

    return {
        "storeId": ci["storeId"],
        "customerItemId": ci["customerItemId"],
        "name": _plain_name(ci["name"]),
        "photoUrl": ci.get("photoUrl"),
        "quantity": ci["quantity"],
        "note": ci.get("note") or "",
        "price": _money_input(ci["price"]),
        "modifiers": [mod(m) for m in ci.get("modifiers") or []],
    }


def _plain_name(name: Any) -> str:
    return name.get("value", "") if isinstance(name, dict) else name or ""


def _money_input(m: dict[str, Any]) -> dict[str, Any]:
    return {"currencyCode": m["currencyCode"], "units": m.get("units") or 0, "nanos": m.get("nanos") or 0}


def _line_view(ci: dict[str, Any]) -> dict[str, Any]:
    def mods(ms):
        return [_plain_name(m["name"]) + (f" ×{m['quantity']}" if m["quantity"] > 1 else "")
                + (f" [{', '.join(mods(m['modifiers']))}]" if m.get("modifiers") else "")
                for m in ms or []]

    view = {"name": _plain_name(ci["name"]), "quantity": ci["quantity"], "price": money(ci["price"]),
            "store_id": ci.get("storeId")}
    if ci.get("modifiers"):
        view["modifiers"] = mods(ci["modifiers"])
    if ci.get("note"):
        view["note"] = ci["note"]
    return view


def _cart_view(w: DeliveryWindow, resp: dict[str, Any]) -> dict[str, Any]:
    summary = resp.get("summary") or {}
    return {
        "window": w.view(),
        "items": [{"cart_item_id": ci["cartItemId"], **_line_view(ci["customerItem"])}
                  for ci in resp["cart"]["customerItems"]],
        "subtotal": money(summary.get("subtotal")),
        "tax": money(summary.get("tax")),
        "discount": money(summary.get("discount")),
        "total_due": money(summary.get("total")),
        "issues": resp.get("validationIssues") or [],
    }


def _entry_view(e: dict[str, Any], stores: dict[str, Any]) -> dict[str, Any]:
    info, state = e["deliveryInfo"], e.get("state") or {}
    if state.get("cancelledAt"):
        status = "cancelled"
    elif state.get("orderId"):
        status = "ordered"
    elif state.get("skippedReason"):
        status = f"skipped: {state['skippedReason']}"
    elif state.get("orderPlacementFailedReasons"):
        status = "placement_failed"
    else:
        status = "scheduled"
    items = e["meal"]["mealItems"] or []
    return {
        "entry_id": e["id"],
        "date": _parse_ts(info["deliveryWindowStart"]).astimezone(ZoneInfo(info["timezone"])).date().isoformat()
        if info.get("timezone") else info["deliveryWindowStart"][:10],
        "window": info.get("deliveryWindowDisplayName"),
        "place_order_at": info.get("placeOrderAt"),
        "source": e.get("source"),
        "status": status,
        "order_id": state.get("orderId"),
        "restaurants": sorted({stores.get(i["storeId"], {}).get("brandName") or i["storeId"] for i in items}),
        "items": [_line_view(i) for i in items],
        "total": round(sum(money(i["price"]) * i["quantity"] + sum(
            money(m["price"]) * m["quantity"] for m in i.get("modifiers") or []) for i in items), 2),
        **({"problems": state.get("validationErrors") or state.get("orderPlacementFailedReasons")}
           if state.get("validationErrors") or state.get("orderPlacementFailedReasons") else {}),
    }


def _order_view(o: dict[str, Any]) -> dict[str, Any]:
    hub = ((o.get("fulfillmentInfo") or {}).get("delivery") or {}).get("deliveryHubInfo") or {}
    stores = _kv(o.get("storeDataMap"))
    items = (o.get("meal") or {}).get("mealItems") or []
    return {
        "order_id": o["id"],
        "type": o["orderType"],
        "status": o["orderStatus"].removeprefix("ORDER_STATUS_").lower(),
        "placed_at": o.get("orderPlacedAt"),
        "delivery_window_start": hub.get("deliveryWindowStart"),
        "restaurants": sorted({stores.get(i["storeId"], {}).get("brandName") or i["storeId"] for i in items}),
        "items": [_line_view(i) for i in items],
        "total": money((o.get("paymentDetails") or {}).get("total")),
    }


__all__ = ["LineItem", "ModifierChoice", "PicnicInputError", "PicnicService", "ResponseError"]
